[package]
name = "test_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = { version = "0.9.2", features = ["lazy"]}
x86_64 = "=0.14.6"
uart_16550 = "0.2.14"
linked_list_allocator = "0.9.0"
