[package]
name = "fuzz_pe_loader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
td-loader = {path = "../../td-loader"}
afl = { version = "*", optional = true }
scroll = { version = "0.10", default-features=false, features = ["derive"] }

[features]
fuzz = ["afl"]
