[package]
name = "test-runner-client"
version = "0.1.0"
description = "Client cooperating with test-runner-server to execute unit test cases in virtual machines"
repository = "https://github.com/confidential-containers/td-shim"
homepage = "https://github.com/confidential-containers"
license = "Apache 2.0"
edition = "2018"

[dependencies]
linked_list_allocator = "0.9.0"
spin = { version = "0.9.2", features = ["lazy"]}
uart_16550 = "0.2.17"
x86_64 = "0.14.9"
